apiVersion: v1
kind: Template
metadata:
  name: config-manager
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: config-manager
  spec:
    envName: ${ENV_NAME}

    database:
      name: config-manager
      version: 10

    kafkaTopics:
    - replicas: 3
      partitions: 16
      topicName: platform.playbook-dispatcher.runner-updates
    - replicas: 3
      partitions: 16
      topicName: platform.inventory.events

    pods:
    - name: service
      minReplicas: ${{REPLICAS}}
      web: true
      image: ${IMAGE}:${IMAGE_TAG}
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /metrics
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /metrics
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      env:
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: CLOWDER_ENABLED
          value: "true"
        - name: CM_DISPATCHER_PSK
          valueFrom:
            secretKeyRef:
              key: key
              name: psk-playbook-dispatcher
        - name: CM_DISPATCHER_HOST
          value: ${CM_DISPATCHER_HOST}
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: 250m
          memory: 256Mi

parameters:
- name: IMAGE_TAG
  required: true
- name: IMAGE
  value: quay.io/cloudservices/config-manager
- description : ClowdEnvironment name
  name: ENV_NAME
  required: true
- name: LOG_LEVEL
  value: INFO
- name: CPU_LIMIT
  value: 500m
- name: MEMORY_LIMIT
  value: 512Mi
- name: REPLICAS
  value: "2"
- name: CM_DISPATCHER_HOST
  required: true
