---
# This playbook will perform steps required to remove Insights Compliance service from your system.
- hosts: localhost
  become: yes
  tasks:
    - name: Compliance OpenSCAP disabled
      debug:
        msg: "Compliance OpenSCAP is not enabled. Nothing to do"
