---
# Steps required to get your system ready to use the Insights Client:
# 1. Yum install the insights-client
# 2. Register the insights-client
# 3. Modify file permissions
- hosts: all
  become: yes
  tasks:
    - name: Install 'insights-client'
      yum:
        name: insights-client
    - name: Register Insights Client
      command: insights-client --register
