---
# This playbook will take care of all steps required to remove
# Insights Client
- hosts: all
  become: yes
  tasks:
    - name: Unregister the insights-client
      command: insights-client --unregister
    
    - name: Remove Insights Client
      yum:
        name: insights-client
        state: absent
