---
# This playbook will take care of all steps required to remove
# Insights Client
- hosts: localhost
  become: yes
  tasks:
    - name: Unregister the insights-client
      command: insights-client --unregister
